@Sentaur.Leaderboard.Api_HostAddress = http://localhost:5203

GET {{Sentaur.Leaderboard.Api_HostAddress}}/score/
Accept: application/json

###

GET https://sentaur-leaderboard-f7z2cjcdzq-uc.a.run.app/score/
Accept: application/json


###

DELETE https://sentaur-leaderboard-f7z2cjcdzq-uc.a.run.app/score?name=Bracing&score=2621
Accept: application/json
Authorization: Bearer

###

POST https://sentaur-leaderboard-f7z2cjcdzq-uc.a.run.app/token/
Content-Type: application/json

{
  "username": "",
  "password": ""
}


###

POST https://sentaur-leaderboard-f7z2cjcdzq-uc.a.run.app/score/
Content-Type: application/json

{
  "key": "3fa85f64-5717-4562-b3fc-2c963f66afa1",
  "name": "string",
  "email": "string",
  "duration": "00:00:01",
  "score": 0,
  "timestamp": "2024-03-10T18:09:36.589Z"
}
